# Generated by Django 3.2.5 on 2021-08-16 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210816_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),

        migrations.CreateModel(
            name='water_services_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),

        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now),
        ),

        migrations.CreateModel(
            name='Water_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('delivery_time', models.DateTimeField(
                    blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(
                    blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(
                    default=True, on_delete=django.db.models.deletion.CASCADE, to='products.water_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(
                    blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(
                    default=True, on_delete=django.db.models.deletion.CASCADE, to='products.water_services_category')),
            ],
        ),
    ]
