# Generated by Django 3.2.4 on 2021-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210819_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
