# Generated by Django 3.2.4 on 2021-08-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210820_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_services',
            name='category',
        ),
        migrations.RemoveField(
            model_name='water_types',
            name='category',
        ),
        migrations.DeleteModel(
            name='water_categories',
        ),
        migrations.DeleteModel(
            name='Water_Services',
        ),
        migrations.DeleteModel(
            name='water_services_category',
        ),
        migrations.DeleteModel(
            name='Water_Types',
        ),
    ]
