# Generated by Django 3.2.4 on 2021-08-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.water_services'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.water_types'),
        ),
    ]
