# Generated by Django 3.2.4 on 2021-08-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210824_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='services',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='waters',
        ),
    ]
